directories/urls.py
from django.urls import path

from . import views

#/directories/
app_name = "directories"

urlpatterns = [
   path("", views.IndexView.as_view(), name="index"),
   path("stake/<int:pk>/", views.StakeDetailView.as_view(), name="stake"),
   path("ward/<int:pk>/", views.WardDetailView.as_view(), name="ward"),
   path("users/<int:pk>/", views.UserDetailView.as_view(), name="member"),
   path("event/<int:pk", views.EventDetailView.as_view(), name="event"),
   path("<int:stake_id>/add_event/", views.add_event, name="add_event"),
]

ym/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("directories.urls")),
    path('directories/', include("directories.urls")),
    path('admin/', admin.site.urls),
]

directories/models.py
from django.db import models
from django.contrib import admin


class Quorum(models.Model):
   quorum_name = models.TextField("Quorum/Class")
   quorum_min_date = models.DateField("Minimum date cutoff")
   quorum_max_date = models.DateField("Maximum date cutoff")
   
   @admin.display(
      boolean=True,
      ordering="quorum_min_date",
      description="Minimum Cutoff Date",
   )
   def __str__(self):
      return self.quorum_name

class Stake(models.Model):
   name= models.TextField("Stake")

   def __str__(self):
      return self.name

class Ward(models.Model):
   name = models.TextField("Ward")
   stake = models.ForeignKey(Stake, on_delete=models.CASCADE)
   
   def __str__(self):
      return self.name

class Family(models.Model):
   name = models.TextField("Family")
   address = models.TextField("Address")
   
   def __str__(self):
      return self.name

class Calling(models.Model):
   name = models.TextField("Calling")

   class Meta:
      ordering = ["name"]
   
   
   def __str__(self):
      return self.name

class User(models.Model):
   first_name = models.CharField(max_length=50)
   last_name = models.CharField(max_length=50)
   birthdate = models.DateField("Birthday")
   quorum = models.ForeignKey(Quorum, on_delete=models.RESTRICT)
   family = models.ForeignKey(Family, on_delete=models.RESTRICT)
   ward = models.ForeignKey(Ward, on_delete=models.RESTRICT)
   callings = models.ManyToManyField(Calling)

   class Meta:
      ordering = ["last_name"]
   
   
   def __str__(self):
      return f'{self.first_name} {self.last_name}'
   

class Event(models.Model):
   title = models.CharField(max_length=50)
   time = models.TimeField()
   date = models.DateField()
   location = models.CharField(max_length=150)
   description = models.TextField()
   attendees = models.ManyToManyField(User)

   class Meta:
      ordering = ["date"]

   
   def __str__(self):
      return self.title

class Assignment(models.Model):
   title = models.CharField(max_length=100)
   owner = models.ForeignKey(User, on_delete=models.CASCADE)
   event = models.ForeignKey(Event, on_delete=models.CASCADE)

 
   def __str__(self):
      return self.title  

directories/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import User, Ward, Stake, Event


# def index(req):
#    event_list = Event.objects.all()
#    context = {
#       "events": event_list
#    }
#    return render(req, "index.html", context)


class IndexView(generic.ListView):
    template_name = "index.html"

    events = Event.objects.all()

    def get_queryset(self):
        """Return the last five published questions."""
        return Event.objects.order_by("date")

#Ward routes

class WardDetailView(generic.DetailView):
   model = Ward
   template_name = "wards/index.html"

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context["members"] = User.objects.filter(ward=self.object.id)
      return context


# def ward_detail(req, ward_id):
#    ward = get_object_or_404(Ward, pk=ward_id)
#    members_list = User.objects.filter(ward=ward_id)
#    context = {
#    "members_list": members_list,
#    "ward": ward,
#    }
#    return render(req, "wards/index.html", context)


#Stake Routes


class StakeDetailView(generic.DetailView):
   model = Stake
   template_name = "stakes/index.html"
   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context["wards"] = Ward.objects.filter(stake=self.object.id)
      return context

# def stake_detail(req, stake_id):
#    stake = get_object_or_404(Stake, pk=stake_id)
#    wards_list = Ward.objects.filter(stake=stake_id)
#    context = {
#       "wards": wards_list,
#       "stake": stake,
#    }
#    return render(req, "stakes/index.html", context)


#Event Routes
   
class UserDetailView(generic.DetailView):
   template_name = "users/index.html"
   model = User


class EventDetailView(generic.DetailView):
   model = Event
   template_name = "events/index.html"

# def event_detail(req, event_id):
#    event = get_object_or_404(Event, pk=event_id)
#    context = {
#       "event": event,
#    }
#    return render(req, "events/detail.html")

def add_event(req, stake_id):
   stake = get_object_or_404(Stake, pk=stake_id)
   return HttpResponseRedirect(reverse("directories:index", args=(stake_id)))

directories/templates/index.html
<!DOCTYPE html>
<html lang="en">
   <head>
   {% load static %}
   <link rel="stylesheet" href="{%static 'index.css' %}">
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Document</title>
</head>
<body>
   {% comment %} <form action="{% url 'directories:add_event' stake.id %}" method="post">
      {% csrf_token %}
      <fieldset>
          <legend><h1>{{ question.question_text }}</h1></legend>
          {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
          {% for choice in question.choice_set.all %}
              <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
              <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
          {% endfor %}
      </fieldset>
      <input type="submit" value="Vote">
      </form> {% endcomment %}
</body>
</html>

directories/templates/stakes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>{{stake.name}}</title>
</head>
<body>
   {% if wards %}
   <ul>
      {% for ward in wards %}
         <li><a href="{% url 'directories:ward' ward.id %}">{{ward.name}}</a></li>
      {% endfor %}
   </ul>
{% else %}
   <p>This stake has no recorded members</p>
{% endif %}
</body>
</html>

directories/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Document</title>
</head>
<body>
   {{object.first_name}}
</body>
</html>

directories/templates/wards/index.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>{{ward.name}}</title>
</head>
<body>
   {% if members %}
      <ul>
         {% for member in members %}
            <li><a href="/users/{{ member.id }}/">{{member.first_name}} {{member.last_name}}</a></li>
         {% endfor %}
      </ul>
   {% else %}
      <p>This ward has no recorded members</p>
   {% endif %}
</body>
</html>